/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */

using Aas = AasCore.Aas3_0_RC02;  // renamed
using Directory = System.IO.Directory;
using Path = System.IO.Path;

using NUnit.Framework; // can't alias

namespace AasCore.Aas3_0_RC02.Tests
{
    public class TestDescendOnce
    {
        private static void CompareOrRerecordTrace(
            IClass instance,
            string expectedPath)
        {
            var writer = new System.IO.StringWriter();
            foreach (var descendant in instance.DescendOnce())
            {
                switch (descendant)
                {
                    case IIdentifiable identifiable:
                        {
                            writer.WriteLine(
                                $"{identifiable.GetType()} with ID {identifiable.Id}");
                            break;
                        }
                    case IReferable referable:
                        {
                            writer.WriteLine(
                                $"{referable.GetType()} with ID-short {referable.IdShort}");
                            break;
                        }
                    default:
                        {
                            writer.WriteLine(descendant.GetType().Name);
                            break;
                        }
                }
            }

            string got = writer.ToString();

            if (Aas.Tests.Common.RecordMode)
            {
                string? parent = Path.GetDirectoryName(expectedPath);
                if (parent != null)
                {
                    if (!Directory.Exists(parent))
                    {
                        Directory.CreateDirectory(parent);
                    }
                }

                System.IO.File.WriteAllText(expectedPath, got);
            }
            else
            {
                if (!System.IO.File.Exists(expectedPath))
                {
                    throw new System.IO.FileNotFoundException(
                        $"The file with the recorded trace does not exist: {expectedPath}");
                }

                string expected = System.IO.File.ReadAllText(expectedPath);
                Assert.AreEqual(
                    expected.Replace("\r\n", "\n"),
                    got.Replace("\r\n", "\n"),
                    $"The expected trace from {expectedPath} does not match the actual one");
            }
        }

        [Test]
        public void Test_Extension()
        {
            Aas.Extension instance = (
                Aas.Tests.CommonJsonization.LoadCompleteExtension());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Extension",
                    "complete.json.trace"));
        }  // public void Test_Extension

        [Test]
        public void Test_AdministrativeInformation()
        {
            Aas.AdministrativeInformation instance = (
                Aas.Tests.CommonJsonization.LoadCompleteAdministrativeInformation());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "AdministrativeInformation",
                    "complete.json.trace"));
        }  // public void Test_AdministrativeInformation

        [Test]
        public void Test_Qualifier()
        {
            Aas.Qualifier instance = (
                Aas.Tests.CommonJsonization.LoadCompleteQualifier());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Qualifier",
                    "complete.json.trace"));
        }  // public void Test_Qualifier

        [Test]
        public void Test_AssetAdministrationShell()
        {
            Aas.AssetAdministrationShell instance = (
                Aas.Tests.CommonJsonization.LoadCompleteAssetAdministrationShell());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "AssetAdministrationShell",
                    "complete.json.trace"));
        }  // public void Test_AssetAdministrationShell

        [Test]
        public void Test_AssetInformation()
        {
            Aas.AssetInformation instance = (
                Aas.Tests.CommonJsonization.LoadCompleteAssetInformation());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "AssetInformation",
                    "complete.json.trace"));
        }  // public void Test_AssetInformation

        [Test]
        public void Test_Resource()
        {
            Aas.Resource instance = (
                Aas.Tests.CommonJsonization.LoadCompleteResource());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Resource",
                    "complete.json.trace"));
        }  // public void Test_Resource

        [Test]
        public void Test_SpecificAssetId()
        {
            Aas.SpecificAssetId instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSpecificAssetId());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "SpecificAssetId",
                    "complete.json.trace"));
        }  // public void Test_SpecificAssetId

        [Test]
        public void Test_Submodel()
        {
            Aas.Submodel instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSubmodel());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Submodel",
                    "complete.json.trace"));
        }  // public void Test_Submodel

        [Test]
        public void Test_RelationshipElement()
        {
            Aas.RelationshipElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteRelationshipElement());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "RelationshipElement",
                    "complete.json.trace"));
        }  // public void Test_RelationshipElement

        [Test]
        public void Test_SubmodelElementList()
        {
            Aas.SubmodelElementList instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSubmodelElementList());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "SubmodelElementList",
                    "complete.json.trace"));
        }  // public void Test_SubmodelElementList

        [Test]
        public void Test_SubmodelElementCollection()
        {
            Aas.SubmodelElementCollection instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSubmodelElementCollection());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "SubmodelElementCollection",
                    "complete.json.trace"));
        }  // public void Test_SubmodelElementCollection

        [Test]
        public void Test_Property()
        {
            Aas.Property instance = (
                Aas.Tests.CommonJsonization.LoadCompleteProperty());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Property",
                    "complete.json.trace"));
        }  // public void Test_Property

        [Test]
        public void Test_MultiLanguageProperty()
        {
            Aas.MultiLanguageProperty instance = (
                Aas.Tests.CommonJsonization.LoadCompleteMultiLanguageProperty());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "MultiLanguageProperty",
                    "complete.json.trace"));
        }  // public void Test_MultiLanguageProperty

        [Test]
        public void Test_Range()
        {
            Aas.Range instance = (
                Aas.Tests.CommonJsonization.LoadCompleteRange());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Range",
                    "complete.json.trace"));
        }  // public void Test_Range

        [Test]
        public void Test_ReferenceElement()
        {
            Aas.ReferenceElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteReferenceElement());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "ReferenceElement",
                    "complete.json.trace"));
        }  // public void Test_ReferenceElement

        [Test]
        public void Test_Blob()
        {
            Aas.Blob instance = (
                Aas.Tests.CommonJsonization.LoadCompleteBlob());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Blob",
                    "complete.json.trace"));
        }  // public void Test_Blob

        [Test]
        public void Test_File()
        {
            Aas.File instance = (
                Aas.Tests.CommonJsonization.LoadCompleteFile());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "File",
                    "complete.json.trace"));
        }  // public void Test_File

        [Test]
        public void Test_AnnotatedRelationshipElement()
        {
            Aas.AnnotatedRelationshipElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteAnnotatedRelationshipElement());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "AnnotatedRelationshipElement",
                    "complete.json.trace"));
        }  // public void Test_AnnotatedRelationshipElement

        [Test]
        public void Test_Entity()
        {
            Aas.Entity instance = (
                Aas.Tests.CommonJsonization.LoadCompleteEntity());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Entity",
                    "complete.json.trace"));
        }  // public void Test_Entity

        [Test]
        public void Test_EventPayload()
        {
            Aas.EventPayload instance = (
                Aas.Tests.CommonJsonization.LoadCompleteEventPayload());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "EventPayload",
                    "complete.json.trace"));
        }  // public void Test_EventPayload

        [Test]
        public void Test_BasicEventElement()
        {
            Aas.BasicEventElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteBasicEventElement());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "BasicEventElement",
                    "complete.json.trace"));
        }  // public void Test_BasicEventElement

        [Test]
        public void Test_Operation()
        {
            Aas.Operation instance = (
                Aas.Tests.CommonJsonization.LoadCompleteOperation());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Operation",
                    "complete.json.trace"));
        }  // public void Test_Operation

        [Test]
        public void Test_OperationVariable()
        {
            Aas.OperationVariable instance = (
                Aas.Tests.CommonJsonization.LoadCompleteOperationVariable());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "OperationVariable",
                    "complete.json.trace"));
        }  // public void Test_OperationVariable

        [Test]
        public void Test_Capability()
        {
            Aas.Capability instance = (
                Aas.Tests.CommonJsonization.LoadCompleteCapability());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Capability",
                    "complete.json.trace"));
        }  // public void Test_Capability

        [Test]
        public void Test_ConceptDescription()
        {
            Aas.ConceptDescription instance = (
                Aas.Tests.CommonJsonization.LoadCompleteConceptDescription());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "ConceptDescription",
                    "complete.json.trace"));
        }  // public void Test_ConceptDescription

        [Test]
        public void Test_Reference()
        {
            Aas.Reference instance = (
                Aas.Tests.CommonJsonization.LoadCompleteReference());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Reference",
                    "complete.json.trace"));
        }  // public void Test_Reference

        [Test]
        public void Test_Key()
        {
            Aas.Key instance = (
                Aas.Tests.CommonJsonization.LoadCompleteKey());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Key",
                    "complete.json.trace"));
        }  // public void Test_Key

        [Test]
        public void Test_LangString()
        {
            Aas.LangString instance = (
                Aas.Tests.CommonJsonization.LoadCompleteLangString());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "LangString",
                    "complete.json.trace"));
        }  // public void Test_LangString

        [Test]
        public void Test_Environment()
        {
            Aas.Environment instance = (
                Aas.Tests.CommonJsonization.LoadCompleteEnvironment());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "Environment",
                    "complete.json.trace"));
        }  // public void Test_Environment

        [Test]
        public void Test_EmbeddedDataSpecification()
        {
            Aas.EmbeddedDataSpecification instance = (
                Aas.Tests.CommonJsonization.LoadCompleteEmbeddedDataSpecification());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "EmbeddedDataSpecification",
                    "complete.json.trace"));
        }  // public void Test_EmbeddedDataSpecification

        [Test]
        public void Test_ValueReferencePair()
        {
            Aas.ValueReferencePair instance = (
                Aas.Tests.CommonJsonization.LoadCompleteValueReferencePair());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "ValueReferencePair",
                    "complete.json.trace"));
        }  // public void Test_ValueReferencePair

        [Test]
        public void Test_ValueList()
        {
            Aas.ValueList instance = (
                Aas.Tests.CommonJsonization.LoadCompleteValueList());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "ValueList",
                    "complete.json.trace"));
        }  // public void Test_ValueList

        [Test]
        public void Test_DataSpecificationIec61360()
        {
            Aas.DataSpecificationIec61360 instance = (
                Aas.Tests.CommonJsonization.LoadCompleteDataSpecificationIec61360());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "DataSpecificationIEC61360",
                    "complete.json.trace"));
        }  // public void Test_DataSpecificationIec61360

        [Test]
        public void Test_DataSpecificationPhysicalUnit()
        {
            Aas.DataSpecificationPhysicalUnit instance = (
                Aas.Tests.CommonJsonization.LoadCompleteDataSpecificationPhysicalUnit());

            CompareOrRerecordTrace(
                instance,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "DescendOnce",
                    "DataSpecificationPhysicalUnit",
                    "complete.json.trace"));
        }  // public void Test_DataSpecificationPhysicalUnit
    }  // class TestDescendOnce
}  // namespace AasCore.Aas3_0_RC02.Tests

/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */
