/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */

using Aas = AasCore.Aas3_0_RC02;  // renamed

using NUnit.Framework; // can't alias

namespace AasCore.Aas3_0_RC02.Tests
{
    /// <summary>
    /// Test de/serialization of classes contained in a container <i>outside</i>
    /// of that container.
    /// </summary>
    /// <remarks>
    /// This is necessary so that we also test the methods that directly de/serialize
    /// an instance in rare use cases where it does not reside within a container such
    /// as <see cref="Aas.Environment" />.
    /// </remarks>
    public class TestXmlizationOfConcreteClassesOutsideContainer
    {
        [Test]
        public void Test_round_trip_Extension()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteExtension();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.ExtensionFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Extension

        [Test]
        public void Test_round_trip_AdministrativeInformation()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteAdministrativeInformation();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.AdministrativeInformationFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_AdministrativeInformation

        [Test]
        public void Test_round_trip_Qualifier()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteQualifier();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.QualifierFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Qualifier

        [Test]
        public void Test_round_trip_AssetAdministrationShell()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteAssetAdministrationShell();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.AssetAdministrationShellFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_AssetAdministrationShell

        [Test]
        public void Test_round_trip_AssetInformation()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteAssetInformation();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.AssetInformationFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_AssetInformation

        [Test]
        public void Test_round_trip_Resource()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteResource();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.ResourceFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Resource

        [Test]
        public void Test_round_trip_SpecificAssetId()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteSpecificAssetId();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.SpecificAssetIdFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_SpecificAssetId

        [Test]
        public void Test_round_trip_Submodel()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteSubmodel();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.SubmodelFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Submodel

        [Test]
        public void Test_round_trip_RelationshipElement()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteRelationshipElement();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.RelationshipElementFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_RelationshipElement

        [Test]
        public void Test_round_trip_SubmodelElementList()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteSubmodelElementList();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.SubmodelElementListFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_SubmodelElementList

        [Test]
        public void Test_round_trip_SubmodelElementCollection()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteSubmodelElementCollection();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.SubmodelElementCollectionFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_SubmodelElementCollection

        [Test]
        public void Test_round_trip_Property()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteProperty();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.PropertyFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Property

        [Test]
        public void Test_round_trip_MultiLanguageProperty()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteMultiLanguageProperty();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.MultiLanguagePropertyFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_MultiLanguageProperty

        [Test]
        public void Test_round_trip_Range()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteRange();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.RangeFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Range

        [Test]
        public void Test_round_trip_ReferenceElement()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteReferenceElement();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.ReferenceElementFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_ReferenceElement

        [Test]
        public void Test_round_trip_Blob()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteBlob();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.BlobFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Blob

        [Test]
        public void Test_round_trip_File()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteFile();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.FileFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_File

        [Test]
        public void Test_round_trip_AnnotatedRelationshipElement()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteAnnotatedRelationshipElement();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.AnnotatedRelationshipElementFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_AnnotatedRelationshipElement

        [Test]
        public void Test_round_trip_Entity()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteEntity();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.EntityFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Entity

        [Test]
        public void Test_round_trip_BasicEventElement()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteBasicEventElement();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.BasicEventElementFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_BasicEventElement

        [Test]
        public void Test_round_trip_Operation()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteOperation();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.OperationFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Operation

        [Test]
        public void Test_round_trip_OperationVariable()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteOperationVariable();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.OperationVariableFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_OperationVariable

        [Test]
        public void Test_round_trip_Capability()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteCapability();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.CapabilityFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Capability

        [Test]
        public void Test_round_trip_ConceptDescription()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteConceptDescription();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.ConceptDescriptionFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_ConceptDescription

        [Test]
        public void Test_round_trip_Reference()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteReference();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.ReferenceFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Reference

        [Test]
        public void Test_round_trip_Key()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteKey();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.KeyFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_Key

        [Test]
        public void Test_round_trip_LangString()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteLangString();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.LangStringFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_LangString

        [Test]
        public void Test_round_trip_EmbeddedDataSpecification()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteEmbeddedDataSpecification();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.EmbeddedDataSpecificationFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_EmbeddedDataSpecification

        [Test]
        public void Test_round_trip_ValueReferencePair()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteValueReferencePair();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.ValueReferencePairFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_ValueReferencePair

        [Test]
        public void Test_round_trip_ValueList()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteValueList();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.ValueListFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_ValueList

        [Test]
        public void Test_round_trip_DataSpecificationIec61360()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteDataSpecificationIec61360();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.DataSpecificationIec61360From(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_DataSpecificationIec61360

        [Test]
        public void Test_round_trip_DataSpecificationPhysicalUnit()
        {
            // We load from JSON here just to jump-start the round trip.
            // The round-trip goes then over XML.
            var instance = Aas.Tests.CommonJsonization.LoadCompleteDataSpecificationPhysicalUnit();

            // The round-trip starts here.
            var outputBuilder = new System.Text.StringBuilder();

            // Serialize to XML
            {
                using var xmlWriter = System.Xml.XmlWriter.Create(
                    outputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    instance,
                    xmlWriter);
            }

            // De-serialize from XML
            string outputText = outputBuilder.ToString();

            using var outputReader = new System.IO.StringReader(outputText);

            using var xmlReader = System.Xml.XmlReader.Create(
                outputReader,
                new System.Xml.XmlReaderSettings());

            var anotherInstance = Aas.Xmlization.Deserialize.DataSpecificationPhysicalUnitFrom(
                xmlReader);

            // Serialize back to XML
            var anotherOutputBuilder = new System.Text.StringBuilder();

            {
                using var anotherXmlWriter = System.Xml.XmlWriter.Create(
                    anotherOutputBuilder,
                    new System.Xml.XmlWriterSettings()
                    {
                        Encoding = System.Text.Encoding.UTF8,
                        OmitXmlDeclaration = true
                    });

                Aas.Xmlization.Serialize.To(
                    anotherInstance,
                    anotherXmlWriter);
            }

            // Compare
            Assert.AreEqual(outputText, anotherOutputBuilder.ToString());
        }  // public void Test_round_trip_DataSpecificationPhysicalUnit
    }  // class TestXmlizationOfConcreteClassesOutsideContainer
}  // namespace AasCore.Aas3_0_RC02.Tests

/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */
