/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */

using Directory = System.IO.Directory;
using Nodes = System.Text.Json.Nodes;
using Path = System.IO.Path;

using NUnit.Framework;  // can't alias

using Aas = AasCore.Aas3_0_RC02;  // renamed

namespace AasCore.Aas3_0_RC02.Tests
{
    public class TestXOrDefault
    {
        private static void CompareOrRerecordValue(
            object value,
            string expectedPath)
        {
            Nodes.JsonNode got = Aas.Tests.CommonJson.ToJson(
                value);

            if (Aas.Tests.Common.RecordMode)
            {
                string? parent = Path.GetDirectoryName(expectedPath);
                if (parent != null)
                {
                    if (!Directory.Exists(parent))
                    {
                        Directory.CreateDirectory(parent);
                    }
                }

                System.IO.File.WriteAllText(
                    expectedPath, got.ToJsonString());
            }
            else
            {
                if (!System.IO.File.Exists(expectedPath))
                {
                    throw new System.IO.FileNotFoundException(
                        $"The file with the recorded value does not exist: {expectedPath}");
                }

                Nodes.JsonNode expected = Aas.Tests.CommonJson.ReadFromFile(
                    expectedPath);

                Aas.Tests.CommonJson.CheckJsonNodesEqual(
                    expected, got, out Aas.Reporting.Error? error);

                if (error != null)
                {
                    Assert.Fail(
                        $"The original value from {expectedPath} is unequal the obtain value " +
                        "when serialized to JSON: " +
                        $"{Reporting.GenerateJsonPath(error.PathSegments)}: " +
                        error.Cause
                    );
                }
            }
        }

        [Test]
        public void Test_Extension_ValueTypeOrDefault_non_default()
        {
            Aas.Extension instance = (
                Aas.Tests.CommonJsonization.LoadCompleteExtension());

            string value = Aas.Stringification.ToString(
                instance.ValueTypeOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Extension",
                    "ValueTypeOrDefault.non-default.json"));
        }  // public void Test_Extension_ValueTypeOrDefault_non_default

        [Test]
        public void Test_Extension_ValueTypeOrDefault_default()
        {
            Aas.Extension instance = (
                Aas.Tests.CommonJsonization.LoadMinimalExtension());

            string value = Aas.Stringification.ToString(
                instance.ValueTypeOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Extension",
                    "ValueTypeOrDefault.default.json"));
        }  // public void Test_Extension_ValueTypeOrDefault_default

        [Test]
        public void Test_Qualifier_KindOrDefault_non_default()
        {
            Aas.Qualifier instance = (
                Aas.Tests.CommonJsonization.LoadCompleteQualifier());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Qualifier",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Qualifier_KindOrDefault_non_default

        [Test]
        public void Test_Qualifier_KindOrDefault_default()
        {
            Aas.Qualifier instance = (
                Aas.Tests.CommonJsonization.LoadMinimalQualifier());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Qualifier",
                    "KindOrDefault.default.json"));
        }  // public void Test_Qualifier_KindOrDefault_default

        [Test]
        public void Test_Submodel_KindOrDefault_non_default()
        {
            Aas.Submodel instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSubmodel());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Submodel",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Submodel_KindOrDefault_non_default

        [Test]
        public void Test_Submodel_KindOrDefault_default()
        {
            Aas.Submodel instance = (
                Aas.Tests.CommonJsonization.LoadMinimalSubmodel());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Submodel",
                    "KindOrDefault.default.json"));
        }  // public void Test_Submodel_KindOrDefault_default

        [Test]
        public void Test_RelationshipElement_KindOrDefault_non_default()
        {
            Aas.RelationshipElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteRelationshipElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "RelationshipElement",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_RelationshipElement_KindOrDefault_non_default

        [Test]
        public void Test_RelationshipElement_KindOrDefault_default()
        {
            Aas.RelationshipElement instance = (
                Aas.Tests.CommonJsonization.LoadMinimalRelationshipElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "RelationshipElement",
                    "KindOrDefault.default.json"));
        }  // public void Test_RelationshipElement_KindOrDefault_default

        [Test]
        public void Test_SubmodelElementList_KindOrDefault_non_default()
        {
            Aas.SubmodelElementList instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSubmodelElementList());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "SubmodelElementList",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_SubmodelElementList_KindOrDefault_non_default

        [Test]
        public void Test_SubmodelElementList_KindOrDefault_default()
        {
            Aas.SubmodelElementList instance = (
                Aas.Tests.CommonJsonization.LoadMinimalSubmodelElementList());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "SubmodelElementList",
                    "KindOrDefault.default.json"));
        }  // public void Test_SubmodelElementList_KindOrDefault_default

        [Test]
        public void Test_SubmodelElementList_OrderRelevantOrDefault_non_default()
        {
            Aas.SubmodelElementList instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSubmodelElementList());

            var value = instance.OrderRelevantOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "SubmodelElementList",
                    "OrderRelevantOrDefault.non-default.json"));
        }  // public void Test_SubmodelElementList_OrderRelevantOrDefault_non_default

        [Test]
        public void Test_SubmodelElementList_OrderRelevantOrDefault_default()
        {
            Aas.SubmodelElementList instance = (
                Aas.Tests.CommonJsonization.LoadMinimalSubmodelElementList());

            var value = instance.OrderRelevantOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "SubmodelElementList",
                    "OrderRelevantOrDefault.default.json"));
        }  // public void Test_SubmodelElementList_OrderRelevantOrDefault_default

        [Test]
        public void Test_SubmodelElementCollection_KindOrDefault_non_default()
        {
            Aas.SubmodelElementCollection instance = (
                Aas.Tests.CommonJsonization.LoadCompleteSubmodelElementCollection());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "SubmodelElementCollection",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_SubmodelElementCollection_KindOrDefault_non_default

        [Test]
        public void Test_SubmodelElementCollection_KindOrDefault_default()
        {
            Aas.SubmodelElementCollection instance = (
                Aas.Tests.CommonJsonization.LoadMinimalSubmodelElementCollection());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "SubmodelElementCollection",
                    "KindOrDefault.default.json"));
        }  // public void Test_SubmodelElementCollection_KindOrDefault_default

        [Test]
        public void Test_Property_KindOrDefault_non_default()
        {
            Aas.Property instance = (
                Aas.Tests.CommonJsonization.LoadCompleteProperty());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Property",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Property_KindOrDefault_non_default

        [Test]
        public void Test_Property_KindOrDefault_default()
        {
            Aas.Property instance = (
                Aas.Tests.CommonJsonization.LoadMinimalProperty());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Property",
                    "KindOrDefault.default.json"));
        }  // public void Test_Property_KindOrDefault_default

        [Test]
        public void Test_Property_CategoryOrDefault_non_default()
        {
            Aas.Property instance = (
                Aas.Tests.CommonJsonization.LoadCompleteProperty());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Property",
                    "CategoryOrDefault.non-default.json"));
        }  // public void Test_Property_CategoryOrDefault_non_default

        [Test]
        public void Test_Property_CategoryOrDefault_default()
        {
            Aas.Property instance = (
                Aas.Tests.CommonJsonization.LoadMinimalProperty());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Property",
                    "CategoryOrDefault.default.json"));
        }  // public void Test_Property_CategoryOrDefault_default

        [Test]
        public void Test_MultiLanguageProperty_KindOrDefault_non_default()
        {
            Aas.MultiLanguageProperty instance = (
                Aas.Tests.CommonJsonization.LoadCompleteMultiLanguageProperty());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "MultiLanguageProperty",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_MultiLanguageProperty_KindOrDefault_non_default

        [Test]
        public void Test_MultiLanguageProperty_KindOrDefault_default()
        {
            Aas.MultiLanguageProperty instance = (
                Aas.Tests.CommonJsonization.LoadMinimalMultiLanguageProperty());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "MultiLanguageProperty",
                    "KindOrDefault.default.json"));
        }  // public void Test_MultiLanguageProperty_KindOrDefault_default

        [Test]
        public void Test_MultiLanguageProperty_CategoryOrDefault_non_default()
        {
            Aas.MultiLanguageProperty instance = (
                Aas.Tests.CommonJsonization.LoadCompleteMultiLanguageProperty());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "MultiLanguageProperty",
                    "CategoryOrDefault.non-default.json"));
        }  // public void Test_MultiLanguageProperty_CategoryOrDefault_non_default

        [Test]
        public void Test_MultiLanguageProperty_CategoryOrDefault_default()
        {
            Aas.MultiLanguageProperty instance = (
                Aas.Tests.CommonJsonization.LoadMinimalMultiLanguageProperty());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "MultiLanguageProperty",
                    "CategoryOrDefault.default.json"));
        }  // public void Test_MultiLanguageProperty_CategoryOrDefault_default

        [Test]
        public void Test_Range_KindOrDefault_non_default()
        {
            Aas.Range instance = (
                Aas.Tests.CommonJsonization.LoadCompleteRange());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Range",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Range_KindOrDefault_non_default

        [Test]
        public void Test_Range_KindOrDefault_default()
        {
            Aas.Range instance = (
                Aas.Tests.CommonJsonization.LoadMinimalRange());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Range",
                    "KindOrDefault.default.json"));
        }  // public void Test_Range_KindOrDefault_default

        [Test]
        public void Test_Range_CategoryOrDefault_non_default()
        {
            Aas.Range instance = (
                Aas.Tests.CommonJsonization.LoadCompleteRange());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Range",
                    "CategoryOrDefault.non-default.json"));
        }  // public void Test_Range_CategoryOrDefault_non_default

        [Test]
        public void Test_Range_CategoryOrDefault_default()
        {
            Aas.Range instance = (
                Aas.Tests.CommonJsonization.LoadMinimalRange());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Range",
                    "CategoryOrDefault.default.json"));
        }  // public void Test_Range_CategoryOrDefault_default

        [Test]
        public void Test_ReferenceElement_KindOrDefault_non_default()
        {
            Aas.ReferenceElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteReferenceElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "ReferenceElement",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_ReferenceElement_KindOrDefault_non_default

        [Test]
        public void Test_ReferenceElement_KindOrDefault_default()
        {
            Aas.ReferenceElement instance = (
                Aas.Tests.CommonJsonization.LoadMinimalReferenceElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "ReferenceElement",
                    "KindOrDefault.default.json"));
        }  // public void Test_ReferenceElement_KindOrDefault_default

        [Test]
        public void Test_ReferenceElement_CategoryOrDefault_non_default()
        {
            Aas.ReferenceElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteReferenceElement());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "ReferenceElement",
                    "CategoryOrDefault.non-default.json"));
        }  // public void Test_ReferenceElement_CategoryOrDefault_non_default

        [Test]
        public void Test_ReferenceElement_CategoryOrDefault_default()
        {
            Aas.ReferenceElement instance = (
                Aas.Tests.CommonJsonization.LoadMinimalReferenceElement());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "ReferenceElement",
                    "CategoryOrDefault.default.json"));
        }  // public void Test_ReferenceElement_CategoryOrDefault_default

        [Test]
        public void Test_Blob_KindOrDefault_non_default()
        {
            Aas.Blob instance = (
                Aas.Tests.CommonJsonization.LoadCompleteBlob());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Blob",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Blob_KindOrDefault_non_default

        [Test]
        public void Test_Blob_KindOrDefault_default()
        {
            Aas.Blob instance = (
                Aas.Tests.CommonJsonization.LoadMinimalBlob());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Blob",
                    "KindOrDefault.default.json"));
        }  // public void Test_Blob_KindOrDefault_default

        [Test]
        public void Test_Blob_CategoryOrDefault_non_default()
        {
            Aas.Blob instance = (
                Aas.Tests.CommonJsonization.LoadCompleteBlob());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Blob",
                    "CategoryOrDefault.non-default.json"));
        }  // public void Test_Blob_CategoryOrDefault_non_default

        [Test]
        public void Test_Blob_CategoryOrDefault_default()
        {
            Aas.Blob instance = (
                Aas.Tests.CommonJsonization.LoadMinimalBlob());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Blob",
                    "CategoryOrDefault.default.json"));
        }  // public void Test_Blob_CategoryOrDefault_default

        [Test]
        public void Test_File_KindOrDefault_non_default()
        {
            Aas.File instance = (
                Aas.Tests.CommonJsonization.LoadCompleteFile());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "File",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_File_KindOrDefault_non_default

        [Test]
        public void Test_File_KindOrDefault_default()
        {
            Aas.File instance = (
                Aas.Tests.CommonJsonization.LoadMinimalFile());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "File",
                    "KindOrDefault.default.json"));
        }  // public void Test_File_KindOrDefault_default

        [Test]
        public void Test_File_CategoryOrDefault_non_default()
        {
            Aas.File instance = (
                Aas.Tests.CommonJsonization.LoadCompleteFile());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "File",
                    "CategoryOrDefault.non-default.json"));
        }  // public void Test_File_CategoryOrDefault_non_default

        [Test]
        public void Test_File_CategoryOrDefault_default()
        {
            Aas.File instance = (
                Aas.Tests.CommonJsonization.LoadMinimalFile());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "File",
                    "CategoryOrDefault.default.json"));
        }  // public void Test_File_CategoryOrDefault_default

        [Test]
        public void Test_AnnotatedRelationshipElement_KindOrDefault_non_default()
        {
            Aas.AnnotatedRelationshipElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteAnnotatedRelationshipElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "AnnotatedRelationshipElement",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_AnnotatedRelationshipElement_KindOrDefault_non_default

        [Test]
        public void Test_AnnotatedRelationshipElement_KindOrDefault_default()
        {
            Aas.AnnotatedRelationshipElement instance = (
                Aas.Tests.CommonJsonization.LoadMinimalAnnotatedRelationshipElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "AnnotatedRelationshipElement",
                    "KindOrDefault.default.json"));
        }  // public void Test_AnnotatedRelationshipElement_KindOrDefault_default

        [Test]
        public void Test_Entity_KindOrDefault_non_default()
        {
            Aas.Entity instance = (
                Aas.Tests.CommonJsonization.LoadCompleteEntity());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Entity",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Entity_KindOrDefault_non_default

        [Test]
        public void Test_Entity_KindOrDefault_default()
        {
            Aas.Entity instance = (
                Aas.Tests.CommonJsonization.LoadMinimalEntity());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Entity",
                    "KindOrDefault.default.json"));
        }  // public void Test_Entity_KindOrDefault_default

        [Test]
        public void Test_BasicEventElement_KindOrDefault_non_default()
        {
            Aas.BasicEventElement instance = (
                Aas.Tests.CommonJsonization.LoadCompleteBasicEventElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "BasicEventElement",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_BasicEventElement_KindOrDefault_non_default

        [Test]
        public void Test_BasicEventElement_KindOrDefault_default()
        {
            Aas.BasicEventElement instance = (
                Aas.Tests.CommonJsonization.LoadMinimalBasicEventElement());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "BasicEventElement",
                    "KindOrDefault.default.json"));
        }  // public void Test_BasicEventElement_KindOrDefault_default

        [Test]
        public void Test_Operation_KindOrDefault_non_default()
        {
            Aas.Operation instance = (
                Aas.Tests.CommonJsonization.LoadCompleteOperation());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Operation",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Operation_KindOrDefault_non_default

        [Test]
        public void Test_Operation_KindOrDefault_default()
        {
            Aas.Operation instance = (
                Aas.Tests.CommonJsonization.LoadMinimalOperation());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Operation",
                    "KindOrDefault.default.json"));
        }  // public void Test_Operation_KindOrDefault_default

        [Test]
        public void Test_Capability_KindOrDefault_non_default()
        {
            Aas.Capability instance = (
                Aas.Tests.CommonJsonization.LoadCompleteCapability());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Capability",
                    "KindOrDefault.non-default.json"));
        }  // public void Test_Capability_KindOrDefault_non_default

        [Test]
        public void Test_Capability_KindOrDefault_default()
        {
            Aas.Capability instance = (
                Aas.Tests.CommonJsonization.LoadMinimalCapability());

            string value = Aas.Stringification.ToString(
                instance.KindOrDefault())
                    ?? throw new System.InvalidOperationException(
                        "Failed to stringify the enum");

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "Capability",
                    "KindOrDefault.default.json"));
        }  // public void Test_Capability_KindOrDefault_default

        [Test]
        public void Test_ConceptDescription_CategoryOrDefault_non_default()
        {
            Aas.ConceptDescription instance = (
                Aas.Tests.CommonJsonization.LoadCompleteConceptDescription());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "ConceptDescription",
                    "CategoryOrDefault.non-default.json"));
        }  // public void Test_ConceptDescription_CategoryOrDefault_non_default

        [Test]
        public void Test_ConceptDescription_CategoryOrDefault_default()
        {
            Aas.ConceptDescription instance = (
                Aas.Tests.CommonJsonization.LoadMinimalConceptDescription());

            var value = instance.CategoryOrDefault();

            CompareOrRerecordValue(
                value,
                Path.Combine(
                    Aas.Tests.Common.TestDataDir,
                    "XOrDefault",
                    "ConceptDescription",
                    "CategoryOrDefault.default.json"));
        }  // public void Test_ConceptDescription_CategoryOrDefault_default
    }  // class TestXOrDefault
}  // namespace AasCore.Aas3_0_RC02.Tests

/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */
