"""Generate the test code for the ``DescendOnce`` methods."""

import io
import os
import pathlib
import sys
import textwrap
from typing import List

import aas_core_codegen
import aas_core_codegen.common
import aas_core_codegen.csharp.naming
import aas_core_codegen.naming
import aas_core_codegen.parse
import aas_core_codegen.run
from aas_core_codegen import intermediate
from aas_core_codegen.common import Stripped
from aas_core_codegen.csharp import (
    common as csharp_common
)

from testgen.common import load_symbol_table


def main() -> int:
    """Execute the main routine."""
    symbol_table = load_symbol_table()

    # noinspection PyListCreation
    blocks = []  # type: List[str]

    blocks.append(
        Stripped(
            """\
private static void CompareOrRerecordTrace(
    IClass instance,
    string expectedPath)
{
    var writer = new System.IO.StringWriter();
    foreach (var descendant in instance.DescendOnce())
    {
        switch (descendant)
        {
            case IIdentifiable identifiable:
                {
                    writer.WriteLine(
                        $"{identifiable.GetType()} with ID {identifiable.Id}");
                    break;
                }
            case IReferable referable:
                {
                    writer.WriteLine(
                        $"{referable.GetType()} with ID-short {referable.IdShort}");
                    break;
                }
            default:
                {
                    writer.WriteLine(descendant.GetType().Name);
                    break;
                }
        }
    }

    string got = writer.ToString();

    if (Aas.Tests.Common.RecordMode)
    {
        string? parent = Path.GetDirectoryName(expectedPath);
        if (parent != null)
        {
            if (!Directory.Exists(parent))
            {
                Directory.CreateDirectory(parent);
            }
        }

        System.IO.File.WriteAllText(expectedPath, got);
    }
    else
    {
        if (!System.IO.File.Exists(expectedPath))
        {
            throw new System.IO.FileNotFoundException(
                $"The file with the recorded trace does not exist: {expectedPath}");
        }

        string expected = System.IO.File.ReadAllText(expectedPath);
        Assert.AreEqual(
            expected,
            got,
            $"The expected trace from {expectedPath} does not match the actual one");
    }
}"""
        )
    )

    for symbol in symbol_table.symbols:
        if not isinstance(symbol, intermediate.ConcreteClass):
            continue

        if symbol.name == aas_core_codegen.common.Identifier("Event_payload"):
            # NOTE (mristin, 2022-06-21):
            # Event payload is a dangling class and can not be reached from
            # the environment. Hence, we skip it.
            continue

        cls_name_csharp = aas_core_codegen.csharp.naming.class_name(symbol.name)
        cls_name_json = aas_core_codegen.naming.json_model_type(symbol.name)

        blocks.append(
            Stripped(
                    f"""\
[Test]
public void Test_{cls_name_csharp}()
{{
    string pathToCompleteExample = Path.Combine(
        Aas.Tests.Common.OurTestResourceDir,
        "Json",
        "Expected",
        {csharp_common.string_literal(cls_name_json)},
        "complete.json");
    
    var container = Aas.Tests.CommonJson.LoadInstance(
        pathToCompleteExample);

    var instance = Aas.Tests.Common.MustFind<Aas.{cls_name_csharp}>(
        container);
    
    CompareOrRerecordTrace(
        instance,
        Path.Combine(
            Aas.Tests.Common.OurTestResourceDir,
            "DescendOnce",
            {csharp_common.string_literal(cls_name_json)},
            "complete.json.trace"));
}}  // public void Test_{cls_name_csharp}"""
            )
        )

    writer = io.StringIO()
    writer.write(
        """\
/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */

using Directory = System.IO.Directory;
using Path = System.IO.Path;

using NUnit.Framework; // can't alias

using Aas = AasCore.Aas3_0_RC02;  // renamed

namespace AasCore.Aas3_0_RC02.Tests
{
    public class TestDescendOnce
    {
"""
    )

    for i, block in enumerate(blocks):
        if i > 0:
            writer.write("\n\n")

        writer.write(textwrap.indent(block, "        "))

    writer.write(
        """
    }  // class TestDescendOnce
}  // namespace AasCore.Aas3_0_RC02.Tests

/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */
"""
    )

    this_path = pathlib.Path(os.path.realpath(__file__))
    repo_root = this_path.parent.parent

    target_pth = repo_root / "src/AasCore.Aas3_0_RC02.Tests/TestDescendOnce.cs"
    target_pth.write_text(writer.getvalue(), encoding='utf-8')

    return 0


if __name__ == "__main__":
    sys.exit(main())
